update xbmc

diff --git a/meta-oe/recipes-titan/titan/titan-xbmc/configure.in-helix.patch b/meta-oe/recipes-titan/titan/titan-xbmc/configure.in-helix.patch
--- a/meta-oe/recipes-titan/titan/titan-xbmc/configure.in-helix.patch
+++ b/meta-oe/recipes-titan/titan/titan-xbmc/configure.in-helix.patch
@@ -210,24 +210,6 @@
  
    // Linux assembly is AT&T Unix style, not Intel style
 
---- a/xbmc/cores/AudioEngine/AEFactory.cpp	2015-05-20 09:29:26.000000000 +0200
-+++ a/xbmc/cores/AudioEngine/AEFactory.cpp.patched	2015-05-20 18:07:42.000000000 +0200
-@@ -40,6 +40,7 @@
- 
- bool CAEFactory::LoadEngine()
- {
-+  return true;
-   return CAEFactory::LoadEngine(AE_ENGINE_ACTIVE);
- }
- 
-@@ -78,6 +79,7 @@
- 
- bool CAEFactory::StartEngine()
- {
-+  return true;
-   if (!AE)
-     return false;
- 
 --- a/xbmc/Application.cpp	2015-05-20 09:29:26.000000000 +0200
 +++ a/xbmc/Application.cpp.patched	2015-05-20 18:10:24.000000000 +0200
 @@ -2420,6 +2420,20 @@
@@ -251,3 +233,270 @@
      if (useKeyboard)
      {
        // use the virtualkeyboard section of the keymap, and send keyboard-specific or navigation
+
+--- a/xbmc/cores/AudioEngine/AEFactory.cpp	2015-05-20 09:29:26.000000000 +0200
++++ a/xbmc/cores/AudioEngine/AEFactory.cpp.patched	2015-05-22 18:35:35.000000000 +0200
+@@ -40,7 +40,12 @@
+ 
+ bool CAEFactory::LoadEngine()
+ {
++// oskwon
++#if defined(TARGET_DVBBOX)
++  return true;
++#else
+   return CAEFactory::LoadEngine(AE_ENGINE_ACTIVE);
++#endif /*TARGET_DVBBOX*/
+ }
+ 
+ bool CAEFactory::LoadEngine(enum AEEngine engine)
+@@ -78,6 +83,10 @@
+ 
+ bool CAEFactory::StartEngine()
+ {
++// oskwon
++#if defined(TARGET_DVBBOX)
++  return true;
++#else
+   if (!AE)
+     return false;
+ 
+@@ -87,6 +96,7 @@
+   delete AE;
+   AE = NULL;
+   return false;
++#endif /*TARGET_DVBBOX*/
+ }
+ 
+ bool CAEFactory::Suspend()
+
+--- a/xbmc/utils/CPUInfo.cpp	2015-05-21 12:19:08.000000000 +0200
++++ a/xbmc/utils/CPUInfo.cpp.patched	2015-05-22 18:14:37.000000000 +0200
+@@ -266,7 +266,11 @@
+   if (m_fProcTemperature == NULL)   
+     m_fProcTemperature = fopen("/sys/class/thermal/thermal_zone0/temp", "r");  // On Raspberry PIs
+ 
++#ifdef TARGET_DVBBOX // oskwon
++  m_fCPUFreq = fopen ("/sys/devices/platform/brcmstb/cpu_khz", "r");
++#else
+   m_fCPUFreq = fopen ("/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq", "r");
++#endif
+   if (!m_fCPUFreq)
+   {
+     m_cpuInfoForFreq = true;
+@@ -318,6 +322,29 @@
+           StringUtils::Trim(m_cores[nCurrId].m_strModel);
+         }
+       }
++#ifdef TARGET_DVBBOX // oskwon
++      else if (strncmp(buffer, "system type", strlen("system type"))==0)
++      {
++        char *needle = strstr(buffer, ":");
++        if (needle && strlen(needle)>3)
++        {
++          needle+=2;
++          m_cpuModel = needle;
++          m_cores[nCurrId].m_strModel = m_cpuModel;
++          StringUtils::Trim(m_cores[nCurrId].m_strModel);
++        }
++      }
++      else if (strncmp(buffer, "cpu model", strlen("cpu model"))==0)
++      {
++        char *needle = strstr(buffer, ":");
++        if (needle && strlen(needle)>3)
++        {
++          needle+=2;
++          m_cores[nCurrId].m_strVendor = needle;
++          StringUtils::Trim(m_cores[nCurrId].m_strVendor);
++        }
++      }
++#endif /*TARGET_DVBBOX*/
+       else if (strncmp(buffer, "BogoMIPS", strlen("BogoMIPS"))==0)
+       {
+         char *needle = strstr(buffer, ":");
+
+--- a/xbmc/windowing/egl/EGLWrapper.cpp	2015-05-21 12:19:09.000000000 +0200
++++ a/xbmc/windowing/egl/EGLWrapper.cpp.patched	2015-05-22 18:05:00.000000000 +0200
+@@ -28,6 +28,10 @@
+ #include "EGLNativeTypeIMX.h"
+ #include "EGLWrapper.h"
+ 
++#if defined(TARGET_DVBBOX) // oskwon
++#include "EGLNativeTypeDvbBox.h"
++#endif
++
+ #define CheckError() m_result = eglGetError(); if(m_result != EGL_SUCCESS) CLog::Log(LOGERROR, "EGL error in %s: %x",__FUNCTION__, m_result);
+ 
+ CEGLWrapper::CEGLWrapper()
+@@ -83,6 +87,9 @@
+       (nativeGuess = CreateEGLNativeType<CEGLNativeTypeAndroid>(implementation)) ||
+       (nativeGuess = CreateEGLNativeType<CEGLNativeTypeAmlogic>(implementation)) ||
+       (nativeGuess = CreateEGLNativeType<CEGLNativeTypeRaspberryPI>(implementation)) ||
++#if defined(TARGET_DVBBOX) // oskwon
++      (nativeGuess = CreateEGLNativeType<CEGLNativeTypeDvbBox>(implementation)) ||
++#endif
+       (nativeGuess = CreateEGLNativeType<CEGLNativeTypeIMX>(implementation))
+       )
+   {
+
+--- a/tools/Linux/kodi.sh.in	2015-05-21 12:19:08.000000000 +0200
++++ a/tools/Linux/kodi.sh.in.patched	2015-05-22 18:39:07.000000000 +0200
+@@ -138,11 +138,11 @@
+ }
+ 
+ migrate_home
+-python @datadir@/${bin_name}/FEH.py $SAVED_ARGS
+-RET=$?
+-if [ $RET -ne 0 ]; then
+-  exit $RET
+-fi
++#python @datadir@/${bin_name}/FEH.py $SAVED_ARGS
++#RET=$?
++#if [ $RET -ne 0 ]; then
++#  exit $RET
++#fi
+ 
+ if command_exists gdb; then
+   # Output warning in case ulimit is unsupported by shell
+
+--- a/xbmc/input/linux/LinuxInputDevices.cpp	2015-05-22 18:29:30.000000000 +0200
++++ a/xbmc/input/linux/LinuxInputDevices.cpp.patched	2015-05-22 18:29:03.000000000 +0200
+@@ -255,6 +255,10 @@
+   { 378               , XBMCK_RIGHT       }, // Green
+   { 381               , XBMCK_UP          }, // Yellow
+   { 366               , XBMCK_DOWN        }, // Blue
++#ifdef TARGET_DVBBOX // oskwon
++  { KEY_OK            , XBMCK_RETURN      }, // Ok
++  { KEY_EXIT          , XBMCK_ESCAPE      }, // EXIT
++#endif /*TARGET_DVBBOX*/
+ };
+ 
+ typedef enum
+@@ -527,6 +531,13 @@
+ 
+     KeymapEntry entry;
+     entry.code = code;
++#if defined(TARGET_DVBBOX) // oskwon
++	if (devt.key.keysym.mod & (XBMCKMOD_SHIFT | XBMCKMOD_CAPS)) keyMapValue = entry.shift;
++	else if (devt.key.keysym.mod & XBMCKMOD_ALT) keyMapValue = entry.alt;
++	else if (devt.key.keysym.mod & XBMCKMOD_META) keyMapValue = entry.altShift;
++	else keyMapValue = entry.base;
++	devt.key.keysym.unicode = devt.key.keysym.sym;
++#else
+     if (GetKeymapEntry(entry))
+     {
+       int keyMapValue;
+@@ -544,6 +555,7 @@
+         }
+       }
+     }
++#endif /*defined(TARGET_DVBBOX)*/
+   }
+ 
+   return true;
+@@ -712,6 +724,12 @@
+       break;
+     }
+ 
++#ifdef TARGET_DVBBOX // oskwon
++    if (access("/tmp/playing.lock", F_OK) == 0) {
++    	break;
++    }
++#endif /*TARGET_DVBBOX*/
++
+     //printf("read event readlen = %d device name %s m_fileName %s\n", readlen, m_deviceName, m_fileName.c_str());
+ 
+     // sanity check if we realy read the event
+@@ -956,6 +974,7 @@
+   if (fd < 0)
+     return false;
+ 
++#if !defined(TARGET_DVBBOX) && !VKEY_ENABLE // oskwon
+   if (ioctl(fd, EVIOCGRAB, 1) && errno != EINVAL)
+   {
+     close(fd);
+@@ -963,6 +982,7 @@
+   }
+ 
+   ioctl(fd, EVIOCGRAB, 0);
++#endif /*TARGET_DVBBOX*/
+ 
+   close(fd);
+ 
+@@ -1055,6 +1075,7 @@
+     return false;
+   }
+ 
++#if !defined(TARGET_DVBBOX) && !VKEY_ENABLE // oskwon
+   /* grab device */
+   ret = ioctl(fd, EVIOCGRAB, 1);
+   if (ret && errno != EINVAL)
+@@ -1063,6 +1084,7 @@
+     close(fd);
+     return false;
+   }
++#endif /*TARGET_DVBBOX*/
+ 
+   // Set the socket to non-blocking
+   int opts = 0;
+@@ -1130,7 +1152,9 @@
+ 
+ driver_open_device_error:
+ 
++#if !defined(TARGET_DVBBOX) && !VKEY_ENABLE // oskwon
+   ioctl(fd, EVIOCGRAB, 0);
++#endif /*TARGET_DVBBOX*/
+   if (m_vt_fd >= 0)
+   {
+     close(m_vt_fd);
+@@ -1204,9 +1228,10 @@
+  */
+ void CLinuxInputDevice::Close()
+ {
++#if !defined(TARGET_DVBBOX) && !VKEY_ENABLE // oskwon
+   /* release device */
+   ioctl(m_fd, EVIOCGRAB, 0);
+-
++#endif /*TARGET_DVBBOX*/
+   if (m_vt_fd >= 0)
+     close(m_vt_fd);
+ 
+--- a/xbmc/pvr/addons/PVRClients.cpp	2015-05-22 18:21:46.000000000 +0200
++++ a/xbmc/pvr/addons/PVRClients.cpp.patched	2015-05-22 18:21:14.000000000 +0200
+@@ -1061,7 +1061,7 @@
+     // Please visit http://kodi.wiki/view/PVR to learn more.
+     m_bNoAddonWarningDisplayed = true;
+     CGUIDialogOK::ShowAndGetInput(19271, 19272, 19273, 19274);
+-    CSettings::Get().SetBool("pvrmanager.enabled", false);
++    //CSettings::Get().SetBool("pvrmanager.enabled", false); // oskwon
+     CGUIMessage msg(GUI_MSG_UPDATE, WINDOW_SETTINGS_MYPVR, 0);
+     g_windowManager.SendThreadMessage(msg, WINDOW_SETTINGS_MYPVR);
+   }
+
+--- a/xbmc/utils/StdString.h	2015-05-21 12:19:08.000000000 +0200
++++ a/xbmc/utils/StdString.h.patched	2015-05-22 18:09:17.000000000 +0200
+@@ -1540,6 +1540,12 @@
+ // -----------------------------------------------------------------------------
+ // ssicmp: comparison (case INsensitive, not affected by locale)
+ // -----------------------------------------------------------------------------
++#define NOT_USE_STD (1) /*oskwon*/
++#ifdef NOT_USE_STD
++inline char sstoupper(char ch)    { return (ch >= 'a' && ch <= 'z')? char(ch + 'A' - 'a'): ch; }
++inline char sstolower(char ch)    { return (ch >= 'A' && ch <= 'Z')? char(ch + 'a' - 'A'): ch; }
++#endif
++
+ template<typename CT>
+ inline int ssicmp(const CT* pA1, const CT* pA2)
+ {
+
+--- a/xbmc/system.h	2015-05-21 12:19:08.000000000 +0200
++++ a/xbmc/system.h.patched	2015-05-22 18:19:21.000000000 +0200
+@@ -183,7 +183,9 @@
+ #endif
+ #endif
+ #define HAS_LINUX_NETWORK
++#if !defined(TARGET_DVBBOX) // oskwon
+ #define HAS_LIRC
++#endif /*TARGET_DVBBOX*/
+ #ifdef HAVE_LIBPULSE
+ #define HAS_PULSEAUDIO
+ #endif
